const foods=[
{id:1,ar:'بطاطا اللحم المميزة',en:'Loaded Beef Potato',cat:'Popular',image:'assets/baked-meat.jpg',desc:'بطاطا مخبوزة، جبن كريمي، لحم متبل، ذرة وفلفل.',price:7.5,rating:4.9,badge:'الأكثر طلباً'},
{id:2,ar:'بيتزا الخضار',en:'Veggie Melt Pizza',cat:'Pizza',image:'assets/pizza-veg.jpg',desc:'جبن ذهبي، فطر، زيتون، فلفل وأعشاب.',price:9,rating:4.8,badge:'طازج'},
{id:3,ar:'بيتزا ثلاثية اللحوم',en:'Triple Meat Pizza',cat:'Pizza',image:'assets/pizza-meat.jpg',desc:'بيبروني، نقانق وسلامي مدخن مع جبن غني.',price:11.5,rating:4.9,badge:'مميز'},
{id:4,ar:'بطاطا الذرة الكريمية',en:'Creamy Corn Potato',cat:'Meals',image:'assets/baked-corn.jpg',desc:'ذرة حلوة مع صوص كريمي بالأعشاب.',price:6.5,rating:4.7,badge:'جديد'}];
const cats=[['Popular','الأكثر طلباً'],['Pizza','بيتزا'],['Meals','وجبات'],['Chicken','دجاج'],['Sandwiches','ساندويش'],['Drinks','مشروبات'],['Desserts','حلويات']];
let active='Popular',cart=[]; const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],money=n=>`$${n.toFixed(2)}`;
function renderCats(){ $('#categoryStrip').innerHTML=cats.map(([k,a])=>`<button class="cat-btn ${k===active?'active':''}" data-cat="${k}">${a}<small>${k.toUpperCase()}</small></button>`).join(''); }
function card(f){return `<article class="food-card" data-product="${f.id}"><div class="food-image-wrap"><img src="${f.image}" alt="${f.ar}"></div><div class="food-body"><span class="food-tag">${f.badge}</span><h3>${f.ar}<small>${f.en}</small></h3><p>${f.desc}</p><div class="food-actions"><span class="price">${money(f.price)}</span><button class="round-add" data-add="${f.id}">+</button></div></div></article>`}
function renderFoods(){let list=active==='Popular'?foods:foods.filter(x=>x.cat===active);if(!list.length)list=foods;$('#foodGrid').innerHTML=list.map(card).join('');$('#resultCount').textContent=`${list.length} أطباق`;$('#popularRow').innerHTML=foods.map(f=>`<article class="swipe-card" data-product="${f.id}"><img src="${f.image}" alt="${f.ar}"><div class="swipe-card-body"><h3>${f.ar}<small>${f.en}</small></h3><p>${f.desc}</p><div class="price-row"><b class="price">${money(f.price)}</b><button class="round-add" data-add="${f.id}">+</button></div></div></article>`).join('')}
function updateCart(){const count=cart.reduce((s,x)=>s+x.qty,0),total=cart.reduce((s,x)=>s+x.qty*x.price,0);$('#cartBadge').textContent=count;$('#cartSummary').textContent=`${count} عناصر • ${money(total)}`;$('#cartTotal').textContent=money(total);$('#floatingCart').classList.toggle('visible',count>0);$('#cartItems').innerHTML=count?cart.map(x=>`<div class="cart-item"><img src="${x.image}"><div><h3>${x.ar}<br><small>${x.en}</small></h3><div class="qty"><button data-dec="${x.id}">−</button><span>${x.qty}</span><button data-inc="${x.id}">+</button></div></div><b>${money(x.qty*x.price)}</b></div>`).join(''):'<p>السلة فارغة حالياً<br><small>YOUR CART IS EMPTY</small></p>'}
function add(id){const f=foods.find(x=>x.id===id);const h=cart.find(x=>x.id===id);h?h.qty++:cart.push({...f,qty:1});updateCart();toast('تمت الإضافة للسلة • ADDED TO CART')}
function openSheet(id){$('#sheetBackdrop').classList.add('open');$(id).classList.add('open')};function closeSheets(){$$('.bottom-sheet').forEach(x=>x.classList.remove('open'));$('#sheetBackdrop').classList.remove('open')}
function detail(id){const f=foods.find(x=>x.id===id);$('#detailContent').innerHTML=`<div class="detail-image"><img src="${f.image}"></div><div class="detail-head"><h2>${f.ar}<small>${f.en}</small></h2><p>${f.desc}</p><h3>${money(f.price)}</h3><button class="detail-add" data-add="${f.id}">أضف إلى السلة <small>ADD TO CART</small></button></div>`;openSheet('#detailSheet')}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),1300)}
function intro(){const slides=$$('.intro-dish');let i=0;const timer=setInterval(()=>{slides[i].classList.remove('active');i=(i+1)%slides.length;slides[i].classList.add('active')},1100);setTimeout(()=>{clearInterval(timer);$('#intro').classList.add('hide')},5200);setTimeout(()=>$('#intro')?.remove(),6100)}
function reveal(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1});$$('.reveal').forEach(x=>io.observe(x))}
document.addEventListener('click',e=>{const s=e.target.closest('[data-scroll]');if(s)$(s.dataset.scroll)?.scrollIntoView({behavior:'smooth'});const c=e.target.closest('[data-cat]');if(c){active=c.dataset.cat;renderCats();renderFoods();}const a=e.target.closest('[data-add]');if(a){e.stopPropagation();add(+a.dataset.add);if(e.target.closest('#detailSheet'))closeSheets()}const p=e.target.closest('[data-product]');if(p&&!e.target.closest('button'))detail(+p.dataset.product);if(e.target.closest('#floatingCart')||e.target.closest('#cartNav'))openSheet('#cartSheet');if(e.target.closest('[data-close]')||e.target.id==='sheetBackdrop')closeSheets();const inc=e.target.closest('[data-inc]');if(inc){cart.find(x=>x.id===+inc.dataset.inc).qty++;updateCart()}const dec=e.target.closest('[data-dec]');if(dec){const x=cart.find(x=>x.id===+dec.dataset.dec);x.qty--;if(x.qty<1)cart=cart.filter(y=>y.id!==x.id);updateCart()}});
renderCats();renderFoods();updateCart();reveal();intro();
